inherit_from: .rubocop_todo.yml

AllCops:
  # 除外
  Exclude:
    - 'config.ru'
    - 'bin/**'
    - 'lib/**'
    - 'db/**/*'
    - 'config/**/*'
    - 'script/**/*'
    - 'vendor/**/*'
    - 'tmp/**/*'
  DisplayCopNames: true
  # Rubyバージョン指定
  TargetRubyVersion: 2.6

##################### Style ##################################

# 日本語でのコメントを許可
Style/AsciiComments:
  Enabled: false

# モジュール名::クラス名の定義を許可
Style/ClassAndModuleChildren:
  Enabled: false

# ドキュメントの無い public class を許可する
Style/Documentation:
  Enabled: false

# 桁揃えが綺麗にならないことが多いので migration は除外
Style/ExtraSpacing:
  Exclude:
    - "db/migrate/*.rb"

# 文字列をfreezeするか
Style/FrozenStringLiteralComment:
  Enabled: false
  
# selfが無くても良い時に省略するか。model内において、ローカル変数とメソッド呼び出しの区別をつけた方が分かりやすい場合が多い
Style/RedundantSelf:
  Enabled: false

# ダブルクォートも推奨するか
Style/StringLiterals:
  Enabled: false

################### Layout ##################################

# 禁止 160文字
Layout/LineLength:
  Max: 160
  Exclude:
    - "db/migrate/*.rb"

e